important_columns = [
    'nickname',
    'profile_link',
    'image',
    'age',
    'price',
    'email',
    'phone',
    'about',
    'subjects',
    'type',
    'gender',
    'location',
    'averageLikesCount',
    'averageViewsCount',
    'averageCommentsCount',
    'er',
    #  'averageEr',
    #  'eer',
    'followersCount',
    'followsCount',
    #  'mediaCount',
    'followersRetention',
    'followersLikesPercent',
    'postsCount',
    'male_auditory',
    'female_auditory',
    'public_auditory',
    'estimated_price_exclusive_min',
    'estimated_price_exclusive_max',
    'estimated_price_post_min',
    'estimated_price_post_max',
    'estimated_price_stories_min',
    'estimated_price_stories_max',
    'countries_stats',
    'cities_stats',
    'top_hastags',
    'LQI']

labelup_response = {"https://www.instagram.com/matreshka_on_crocs": "http://labelup.ru/g/a/PNO8yN1hzQxJaQ", "https://www.instagram.com/yuliya_egipet": "http://labelup.ru/g/a/4EitVAWxqoRcaA", "https://www.instagram.com/anna.melek.blog": "http://labelup.ru/g/a/MMvO0DTGhUWsUQ", "https://www.instagram.com/anna_in_saudi": "http://labelup.ru/g/a/7OHV87ZfztM3yg", "https://www.instagram.com/diana.ishkinina": "http://labelup.ru/g/a/Op7QDdASV3WzWg", "https://www.instagram.com/natali_alanya": "http://labelup.ru/g/a/1JjNrMRNp1v_5w", "https://www.instagram.com/psychological_channel": "http://labelup.ru/g/a/q3hD_YA7ZU_V4w", "https://www.instagram.com/elya_aprelya": "http://labelup.ru/g/a/wDzuIdtQLxxrxQ", "https://www.instagram.com/esthetic.gp": "http://labelup.ru/g/a/Q0tH5NpAYARbkw", "https://www.instagram.com/liusi_sahara": "http://labelup.ru/g/a/Hk_SKyrUGkN_bA", "https://www.instagram.com/tati_meeme": "http://labelup.ru/g/a/2eqYc8xGMpwSyw", "https://www.instagram.com/lifeesmoments": "http://labelup.ru/g/a/z00yf0gFRMuX_A", "https://www.instagram.com/tina_ihappy": "http://labelup.ru/g/a/SunaGHVKxkIcPg", "https://www.instagram.com/spain_ny": "http://labelup.ru/g/a/KjchZ5WhllBfaw", "https://www.instagram.com/mixedfamily.life": "http://labelup.ru/g/a/nYA0IXZ1YUJQGA", "https://www.instagram.com/daria.uysal":
                    "http://labelup.ru/g/a/NGHbFoR4Vql_Gg", "https://www.instagram.com/mir.istoriy": "http://labelup.ru/g/a/0TmgDvBJzszQfA", "https://www.instagram.com/hardcore_story": "http://labelup.ru/g/a/sTB60yniEaxDmw", "https://www.instagram.com/podslushano_all": "http://labelup.ru/g/a/pOUGRDJ3bpMy7g", "https://www.instagram.com/podslushanyi.mir": "http://labelup.ru/g/a/DeR_FjcCkDc2QA", "https://www.instagram.com/lera_plammer": "http://labelup.ru/g/a/b21SXxLyKSmYfw", "https://www.instagram.com/mike.around.the.world": "http://labelup.ru/g/a/EFkHvK61jhZjfg", "https://www.instagram.com/elena_mauritius": "http://labelup.ru/g/a/MEJ_Nj_eqsZWjg", "https://www.instagram.com/irinadee_sydney": "http://labelup.ru/g/a/1bqrNcQiz7yAiw", "https://www.instagram.com/evecolours": "http://labelup.ru/g/a/Os_Ygru0RBLs9A", "https://www.instagram.com/zefirka_14": "http://labelup.ru/g/a/inuxxx_uFS3tEQ", "https://www.instagram.com/natasakado": "http://labelup.ru/g/a/VlrTXx5Dx7RGMw", "https://www.instagram.com/katerina_love_spain": "http://labelup.ru/g/a/aneoM1O6Tghk_w", "https://www.instagram.com/mar.ayz": "http://labelup.ru/g/a/DPbsVGGrEP3Blw", "https://www.instagram.com/isv.m": "http://labelup.ru/g/a/pVr9FkYN87DWhQ", "https://www.instagram.com/radistkaaa_ket": "http://labelup.ru/g/a/HCPQgaZDC_0qdg", "https://www.instagram.com/mustardos": "http://labelup.ru/g/a/sdTfi7Y4Pttb1Q"}
